- hosts: webserver
  become: yes
  tasks:
    - name: Pull the new image
      docker_image:
        name: connorfitzgerald/savings-pot-api:latest
    - name: Recreate the Docker service
      docker_service:
        project_name: savings-pot-api
        recreate: always