- hosts: webserver
  become: yes
  tasks:
    - name: Pull the new image
      docker_image:
        name: connorfitzgerald/savings-pot-api:latest
    - name: Recreate the Docker service
      docker_swarm_service:
        name: savings-pot-api
        image: connorfitzgerald/savings-pot-api:latest
        state: present
        force_update: true
        env:
          - "API_PORT=3000"
        publish:
          - published_port: 3000
            target_port: 3000