- hosts: webserver
  become: yes
  tasks:
    - name: Pull the new image
      docker_image:
        name: connorfitzgerald/savings-pot-api:latest
    - name: Re-create the Savings Pot API container
      docker_container:
        name: savings-pot-api
        image: connorfitzgerald/savings-pot-api:latest
        state: started
        recreate: yes
        restart_policy: unless-stopped
        published_ports:
          - 3000:3000
        purge_networks: yes
        networks:
          - name: savings_pot_net
        env:
          API_PORT: "{{ sp_api_port | int }}"
          DB_NAME: "{{ sp_db_name }}"
          DB_PASSWORD: "{{ sp_db_password }}"
          DB_USER: "{{ sp_db_user }}"
          DB_HOST: "{{ sp_db_host }}"
          DB_PORT: "{{ sp_db_port | int }}"