node {
    def app

    stage('Clone repository') 
        checkout scm
    }

    stage('Build') {
        sh 'docker build --target builder -t connorfitzgerald/savings-pot-api:test .'
        sh 'docker build --target runner -t connorfitzgerald/savings-pot-api:latest .'
    }

    stage('Test') {
        sh 'docker container run --rm connorfitzgerald/savings-pot-api:test npm test'
    }

    stage('Push') {
        sh 'docker push connorfitzgerald/savings-pot-api:latest'
    }

    stage('Deploy') {
        ansiColor('xterm') {
            ansiblePlaybook(
                playbook: 'CI/ansible-deploy.yaml',
                colorized: true
            )
        }
    }
}